.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/ci_lint.yml
.github/workflows/ci_unit_test.yml
.github/workflows/deploy_docker.yml
.github/workflows/update_tvm.yml
ci/batch/submit-job.py
cmake/modules/CUTLASS.cmake
docker/batch/entry.sh
docs/wiki/1_getting_start/Build-on-macOS.md
docs/wiki/3_dev_guide/Add-Operator.md
docs/wiki/3_dev_guide/Add-Pass.md
docs/wiki/4_contrib_guide/Development-And-Pull-Request.md
docs/wiki/4_contrib_guide/RFC-Collections.md
python/setup.py
tests/python/frontend/test_pytorch.py

Change repo URL accordingly.
Waiting for Github bot approval to enable CI status updating.

[Repo] Change repo URL

---

.github/workflows/ci_unit_test.yml

The BOT_TOKEN in secret has been updated.

[CI] Enable Github BOT

---

src/op/dialect/nccl/nccl.cc

Fix incompatibility for PR #9 and PR #10

[Bug Fix]Fix incompatibility for PR #9 and PR #10

---

docs/wiki/1_getting_start/Build-on-Ubuntu-18.04.md

[Doc] Update: add install python dependencies

---

include/raf/op.h
src/impl/op.cc
src/op/dialect/cutlass/conv.cc
src/op/dialect/cutlass/cutlass_fusion.cc
src/op/dialect/cutlass/gemm.cc
src/op/dialect/tvm/tvm_utils.h
tests/python/pass/test_pass_estimate_memory.py

A simple PR to make the error messages of op dispatching thread safe.
cc @awslabs/raf-reviewer @yzhliu

[VM] Thread safe error message handling

---

src/op/dialect/cudnn/dropout.cc

Make the required memory in dropout backward as a workspace memory so that it can be considered by the remat pass.
Note that this is just a workaround and doesn't solve the mis-use CuDNN dropout issue mentioned in #36.
cc @awslabs/raf-reviewer @yzhliu @hzfan

[Op] Dropout workspace

---

python/raf/optim/lans.py

Fixed the bug in LANS optimizer with float16 model.

[Bugfix] Fix bug in LANS optimizer with float16 model

---

src/pass/liveness_analysis.cc
tests/python/pass/test_pass_liveness_analysis.py

After constant folding, we may have `let %a2 = (%p0, %a1, tensor(5 x 5, float32))`. In this case, `%a2.2` is created by this tuple, so it should have a liveness var even it is a constant. The current implementation simply uses an undefined var and doesn't track its liveness. This PR fixes this issue and adds a unit test.
cc @awslabs/raf-reviewer @zhouyuan1119

[Pass] Fix liveness analysis with folded constant

---

CMakeLists.txt
include/raf/profiler.h
include/raf/scope_timer.h
src/impl/vm/vm.cc
src/profiler/scope_timer.cc

Refactor the scope timers to better profile the function execution time.

[Misc] Scope Timer

---

docs/wiki/2_user_guide/Train-Model.md

Fixed several import errors of the code presented in the `docs/wiki/2_user_guide/Train-Model.md` file
- [ x ] PR's title starts with a category (e.g. [BUGFIX], [MODEL], [TUTORIAL], [FEATURE], [DOC], etc)

[DOC] fix import errors of the code in "user guide"

---

python/raf/optim/lans.py
src/op/dialect/cuda/lans.cc

Add a group_cast and clean code for LANS, which only takes FP32.

[Bugfix] Fix bugs and clean code for LANS

---

src/pass/switch_train.cc

Minor fix related to SwitchTrainOp pass's name.

[BUGFIX] fix pass name

---

python/raf/distributed/op.py
scripts/src_codegen/def_schema.py
src/op/dialect/nccl/nccl.cc
tests/python/distributed/test_collective_communication.py

add argument rank_list to support reduce_scatter among sectional ranks
bash ci/task_lint.sh passed

[Op] [TVM] update reduce_scatter

---

src/pass/dataflow_matcher.cc
src/pass/dataflow_matcher_impl.h
src/pass/deduplicate.cc

https://github.com/awslabs/raf/pull/69

[TVM] Update Submodule 2022-06-13-13-15-17

---

src/pass/simplify_expr.cc
tests/python/pass/test_pass_simplify_expr.py

Remove dropout if p=0
cc @awslabs/raf-reviewer @XinweiFu @hzfan @comaniac

[Pass] Add simplify dropout

---

CMakeLists.txt
python/setup.py

1. change absolute path to relative path in setup.py for https://stackoverflow.com/questions/18085571/pip-install-error-setup-script-specifies-an-absolute-path
2. add `RAF_INSTALL_DEV` option to install dev header files for other packages to use.
cc @comaniac @hzfan @zachzzc

[Build] a few changes to comply with the internal build system

---

python/raf/frontend/model.py
python/raf/frontend/pytorch.py
python/raf/optim/sgd.py
src/pass/partition_gradient.cc
tests/python/core/test_multi_function_flow.py
tests/python/frontend/test_pytorch.py
tests/python/pass/test_pass_from_relay.py

[Frontend] Distinguish learnable param and non learnable

---

src/op/declare/collective_comm.cc
src/op/ty/collective_comm.cc
tests/python/distributed/test_collective_communication.py

This PR fixes the issues related to the single tensor input for reduce_scatter.

[OP] Reduce_scatter Single tensor input

---

python/raf/_tvm_op/argwhere.py

Minor fix for argwhere

---

python/raf/_tvm_op/reduce.py

Add more configs for sum to achieve better performance.

[OP] More configs for sum

---

python/raf/distributed/config.py
tests/python/distributed/test_config.py

Fix a bug introduced by #68.
cc @awslabs/raf-reviewer @zhen-jia @yetiansh

[Bugfix] Dump dist config causes maximum recursion depth exceeded

---

src/op/ty/collective_comm.cc

[Op] Fix reduce_scatter infertype

---

include/raf/sharding.h
include/raf/value_functor.h
python/raf/_op/imp_utils.py
python/raf/_op/sym_utils.py
python/raf/_tvm_op/__init__.py
python/raf/distributed/sharding/__init__.py
python/raf/distributed/sharding/shardspec.py
python/raf/distributed/sharding/utils.py
python/raf/hybrid/hybrid.py
python/raf/ir/op_utils.py
scripts/src_codegen/def_op.py
src/impl/sharding.cc
src/op/regs/ffi2schema.h
src/op/regs/value2schema.h
src/op/ty/utils.cc
tests/python/pass/test_pass_sharding.py

This PR mainly contains the definition of sharding specifications.

[Dist] RAF Sharding - Phase 1

---

src/pass/liveness_analysis.cc
src/pass/liveness_analysis.h

This should fixes the stack overflow issue when working on large models.

[Liveness] Avoid stack overflow

---

src/pass/rematerialization.cc

This should fix the benchmark (hopefully...)
cc @awslabs/raf-reviewer @zhouyuan1119

[Remat] Fix bug in determining profitable ops
