awslabs/raf

scripts/src_codegen/run_all.sh
Do not run clang-format to auto-generated files as we don't check in them anymore.
cc @awslabs/raf-reviewer @hzfan
=> [Codegen] Don't run clang-format

python/raf/_tvm_op/transform.py, python/raf/distributed/__init__.py, python/raf/distributed/op.py, scripts/src_codegen/def_op.py, scripts/src_codegen/def_schema.py, src/op/declare/collective_comm.cc, src/op/declare/transform.cc, src/op/dialect/nccl/nccl.cc, src/op/dialect/tvm/transform.cc, src/op/ty/collective_comm.cc, src/op/ty/transform.cc, tests/python/distributed/test_collective_communication.py, tests/python/op/tvm/test_tvm_transform.py, tests/python/pass/test_pass_inplace_update.py
This PR implements some group ops for ZeRO optimizations.  
There are 3 group operators:
`group_cast`: cast a tensor list.
`group_allgather`: perform allgather for each tensor in the group. The result is in-place updated. So tensor allocation for this op.  The in-place update implementation may need to refactor after we finish: https://github.com/meta-project/meta/issues/758
`group_reduce_scatter`: perform reduce_scatter for each tensor in the group
=> [OP][Dist] Group ops

src/pass/estimate_flops.cc, tests/python/pass/test_pass_estimate_flops.py
If op does not have a TVM dialect, skip the flops estimation.
=> [PASS] skip non-TVM op in Estimate  flops pass

include/raf/vm/bytecode.h, include/raf/vm/vm.h, scripts/src_codegen/def_schema.py, src/impl/vm/bytecode.cc, src/impl/vm/compiler.cc, src/impl/vm/executable.cc, src/impl/vm/vm.cc, src/pass/memory_plan.cc
In the case of CUDA 11.3, we currently always use AllocSync to allocate memory to CUDA memory pool for better efficiency. However, in the case that allocated tensor becomes the final output, we should not let the CUDA memory pool maintain them to avoid fragmentation issue.
In this PR, we introduce an optional argument, `alloc_async` (`async` becomes a keyword since Python 3.7), to AllocStorage instruction in VM. When it is true (by default), we keep the current semantic of allocating buffers to CUDA memory pool; otherwise we use cuMalloc to allocate a buffer directly from GPU DRAM. This argument will be set by MemoryPlan pass with liveness analysis.
With this PR, Razor can now achieve the same batch size as RAF (i.e., 24) for bert_base_mlm with seq=512, amp, remat.
cc …
=> [VM] Support AllocStorage sync/async

src/pass/liveness_analysis.cc, src/pass/rematerialization.cc, tests/python/pass/test_pass_rematerialization.py
This PR addresses issue #8  and presents a small fix for the rematerialization pass to handle nested tuples. Specifically, it handles cases like the following:
```
...
let a = (x0, x1)
...
let b = some_call()
...
let c = (a, b)
```
Without this patch the remat pass would error out when processing `c` because of a simplified assumption we made in the first version of the pass. **Notice that this fix does not address the case where a call node directly produces a nested tuple (which does not exist in current RAF as far as I know).**
ResNet50 with AMP can now be compiled with rematerialization turned on, and the benchmarked latency is ~35ms per batch when the batch size is 16. 
I will add a test for nested tuples later. Please review the changes first. 
cc @awslabs/raf-reviewer @comaniac
=> [Remat][Bugfix] Enhance the rematerialization pass to handle nested tuples

src/impl/vm/compiler.cc, src/pass/type_infer.cc, tests/python/pass/test_pass_infer_type.py
Closing #27 
With this PR, we should be able to run end-to-end benchmark again.
This PR mainly improves InferType to mutate closure parameter types if there are inconsistent with the caller types. This inconsistent comes from the VM pass sequence (FuseTVM -> DispatchDialect). For example, dispatching `_contrib_dropout` to CuDNN dialect results in type change. In this case, a fused closure that uses the output tensor of the original `_contrib_dropout` will have inconsistent parameter types.
cc @awslabs/raf-reviewer @yzhliu @hgt312 @hzfan please help review this PR carefully as InferType is a core pass and is widely used.
=> [InferType] Fix closure type error

src/pass/type_infer.cc, tests/python/pass/test_pass_infer_type.py
In #28 I forgot to add the updated closure to the visit closure list. As a result, InferType throws an error even a closure is used by two callers with the same type.
cc @awslabs/raf-reviewer @yzhliu @hgt312
=> [Bugfix] Fix bug in #28

src/op/dialect/cutlass/conv.cc, src/op/dialect/cutlass/conv_utils.cc, src/op/dialect/cutlass/conv_utils.h, src/op/dialect/cutlass/cutlass_fusion.cc, src/op/dialect/cutlass/cutlass_utils.cc, src/op/dialect/cutlass/cutlass_utils.h, src/op/dialect/cutlass/gemm.cc, src/op/dialect/cutlass/gemm_utils.cc, src/op/dialect/cutlass/gemm_utils.h, src/op/dialect/tvm/tvm_fusion.cc
Add cache to fused function JITing to reduce the first iteration latency. Specifically, this PR adds two caches for TVM fusion and CUTLASS fusion. Here is the elapsed time of warmup GPT2 on g4.4xl:
|Mode|Time (s)|
--|--
No Cache|483
+Cache TVM fusion|126
+Cache CUTLASS fusion|63
Since we are caching a fused function, I simply use `AsText(func, true)` as the cache key, which includes parameter, output types, and function body.
cc @awslabs/raf-reviewer @hzfan
=> [VM] Cache fused func JIT

include/raf/op_utils.h, src/pass/rematerialization.cc
Non-deterministic ops such as dropout cannot be recomputed; otherwise we may get incorrect results.
cc @awslabs/raf-reviewer @zhouyuan1119
=> [Remat] Do not recompute non-deterministic ops

src/impl/ir_ext.cc, src/impl/serialization.cc, src/op/dialect/cutlass/cutlass_fusion.cc, src/op/dialect/tvm/tvm_fusion.cc
- Use `raf::ir::AsText` as the fused function key to make sure all values (including constant arguments) are considered.
- Fix a bug in VM deserialization that mis-uses TVM JSON decoder which doesn't use ExtendedVar.
cc @awslabs/raf-reviewer @zachzzc @hzfan
=> [Bugfix] Cache fusion JIT / serialization

include/raf/op_utils.h, python/raf/_tvm_op/nn.py, src/op/declare/nn.cc, src/op/dialect/cudnn/cudnn_utils.h, src/op/dialect/cudnn/dropout.cc, src/op/grad/nn.cc, src/op/ty/nn.cc, src/pass/assign_device.cc, src/profiler/op_profiler.cc, tests/python/op/cudnn/test_cudnn_nn.py
Close #36 
This PR fixes the dropout mentioned in the issue. Specifically, we use a global memory manager to maintain random state buffers. As a result, all dropout ops with the same device and ratio could share random state. Although this memory manager cannot be viewed by remat pass, it is just a few MBs so shouldn't be a big problem.
In addition, this PR also changes the `_contrib_dropout` output to be tuple-3 by removing the `out_state`. This has no effect because 1) we don't use this output at all, and 2) the CuDNN dropout OpEnv updates the state inplace, and it doesn't actually copy the state to this output buffer, so it's meaningless.
Finally, this PR removes the trick in AssignDevice pass that adds the optional argument (i.e., `in_states`). Instead, we just don't specify this …
=> [Op] Fix dropout

python/raf/testing/common.py, src/op/from_relay/nn.cc, src/op/grad/binary.cc, tests/python/op/tvm/test_tvm_binary.py
The current derivation of `y=x^a` is `dx = a * x^a / x`. This is problematic and results in `nan` when `x=0`. This PR changes the logic to `dx = a * x ^ (a-1)` to avoid such case.
cc @awslabs/raf-reviewer @yzhliu
=> [Op] Fix power_dx

include/raf/communicator.h, src/device_api/cuda/cuda.cc, src/distributed/common/communicator.cc, src/distributed/cuda/nccl_communicator.cc, src/op/dialect/nccl/nccl.cc
These are the fixes to run distributed CUDA by Razor. In Razor, it uses multi-processes for different ranks, but each rank contains multiple threads(one for trace/compile and others for execution). This requires some changes in RAF. To be more specific, 
1) Communicator Pool and entry needs to be shared within the process. Since we mostly do multiprocessing instead of multithreading for distributed training, I removed the thread local version directly. Let me know if you think we should keep the thread-local version.
2) CUDA needs to call cudaSetDevice for each **THREAD** (both trace/compile and executions threads in Razor), if we use cudaMalloc without specified stream. The memory pool is created in trace/compile thread so I add a device setup before Alloc and NCCL call.
cc …
=> [Fix] Path clearing for Razor distributed execution on GPU

tests/python/pass/test_pass_estimate_memory.py
Close #44 
The flaky should come from the different Conv2D algorithm selection. Now the acceptable memory usage at that op has been enlarged to cover all possibilities.
cc @awslabs/raf-reviewer @hgt312 @zhouyuan1119
=> [Flaky] Correct expected memory in estimate_memory test

scripts/src_codegen/main_cxx_reg.py
Fix the code indent, the `strip()` removes the indent in `if` statement.
cc @comaniac
=> [Autogen] add indent for schema field index if condition in regs.cc

python/raf/frontend/pytorch.py
This PR enables support to more than one model input during tracing.
A `shape_dict` is passed to the `from_pytorch` function, which is a map from input name to its shape, type, and maximal value. The `maximal_value` is optional and set to 10000 by default. 
The reason for adding the `maximal_value` is that when generating example input tensors for tracing, different tensors might require different initialization values. For example, input_ids to the BERT model can be set between 0 to 10000, and valid sequence length can be set between 0 to 128.
This PR also disabled the redundant model evaluation when tracing. `#model(*example_inputs)`
=> [FEATURE] Support multiple inputs

python/raf/_tvm_op/reduce.py, python/raf/_tvm_op/utils.py
1. Include `max_num_thread` and remove 16 in the tuning space. This config is useful when scheduling all reduce workloads.
2. Isolate performance evaluation to another thread to avoid environment inconsistency caused by compilation failure.
=> [Op][TVM] Miner improvements for TOPI tuner

ci/task_build.sh, python/setup.py, scripts/wheel/build_wheel_manylinux.sh
The last PR changed `setup.py` doesn't work for wheel build and breaks the daily benchmark (https://github.com/meta-project/models/runs/6893167470?check_suite_focus=true) due to undefined `LIB_LIST`. This PR changes the following:
- Since we are going to use a bash script to build RAF and only use setup.py for packaging, `get_lib_path()` should be working, so I uncommented `LIB_LIST`.
- Changed the bash script to build wheel instead of source. Ref: https://medium.com/ochrona/understanding-python-package-distribution-types-25d53308a9a
- Try to build wheels in CI to cover any future changes.
cc @awslabs/raf-reviewer @sqsharma
=> [Setup] Fix setup.py for dist build and add test

src/op/grad/nn.cc
Removed the unit test for reciprocal op with gradient on fp16.
Currently, reciprocal op will only run backward pass in fp32.
=> [Op] Use y*y instead of 1/x^2 to calculate reciprocal gradients

CMakeLists.txt
Including all .cc and then exclude cuda etc. source files from RAF_CXX_SOURCE_FILES.
Just make it easier for internal repository to add extra source file directory (e.g., src/amazon)
cc @comaniac @awslabs/raf-reviewer
=> [Build] Exclude cuda etc. source files from RAF_CXX_SOURCE_FILES

python/raf/_tvm_op/utils.py
Somehow (I don't know the reason...) when pushing a `te.Tensor` to a Python set, `__eq__` will be invoked and may trigger the following error if the tensor is rank-0.
```
raf/src/op/dialect/tvm/tvm_fusion.cc:297: Failed to build a fused op fused_multiply_sqrt_cast_greater_add_divide_where_multiply_add_divide_multiply_m_16765600757613373181_: ValueError: Equal == comparison among rank-0 tensor is ambiguous, use Tensor.equal for content expression equvalence, use Tensor.same_as for exact reference comparison
```
This PR uses a custom set that explicitly leverages `same_as` to deduplicate tensors.
=> [Util] Use custom tensor set

python/raf/_tvm_op/loss.py, tests/python/op/tvm/test_tvm_loss.py
This is a compatible change for supporting both one-hot label and a 2-dim label for nll_loss, to be consistent with the internal repository.
cc @comaniac @hzfan @zachzzc
=> [Op] support 2-dim nll_loss label

src/pass/rematerialization.cc
In #96, I placed a wrong data type for memory budget which results in overflow.
=> [Bugfix] Use int64_t for memory budget

src/op/from_relay/nn.cc, tests/python/pass/test_pass_from_relay.py
The dropout op in RAF requires an extra "in_states" argument compared to it in PyTorch. So we make up a NULL in_states argument in from_relay.
=> [Op] Make up in_states arg of dropout in from_relay

python/raf/_tvm_op/loss.py, tests/python/op/tvm/test_tvm_loss.py
due to low precision of fp16, accumulation will produce strange value
change to use fp32 to accumulate, it may degrade the performance
```
In [10]: raf.nll_loss(rb, ra.to(dtype="float32"))
Out[10]:
[9.835546]
<NDArray [1] @ cpu, dtype=float32>
In [11]: raf.nll_loss(rb, ra)
Out[11]:
[4.]
<NDArray [1] @ cpu, dtype=float16>
```
P.S.: I also find that the grad of nll_loss have a bigger difference about 0.0007 when use fp16
@yzhliu @comaniac
=> [Op] Fix nll_loss

.github/workflows/ci_lint.yml, .github/workflows/ci_unit_test.yml, .github/workflows/update_tvm.yml
Github Action changelog:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
In short, `save-output` command is deprecating, so this PR changes them to use environment files accordingly.
=> [CI] Update action deprecating save-output cmd

src/op/from_relay/nn.cc, tests/python/pass/test_pass_from_relay.py
https://github.com/apache/tvm/pull/13927 changes the logic of converting PyTorch batch_matmul to Relay. Specifically, it uses Relay's batch_matmul attribute `transpose_b` to avoid explicitly adding a transpose op. However, the current logic of converting Relay to RAF doesn't consider this attribute and results in incorrect IRs.
This PR thus fixes the Relay to RAF conversion logic to dispatch Relay batch_matmul to one of batch_matmul_xy ops.
=> [Compatible] Fix batch_matmul from Relay

src/op/from_relay/nn.cc, tests/python/pass/test_pass_from_relay.py
I noticed that since the TVM submodule was updated 2 weeks ago, there are significant performance dropping and memory consumption increasing. Since we are not actively working on RAF anymore, I reverted to the last working commit and stopped weekly updating TVM submodule commit.
=> [TVM] Revert submodule updates
